const BingoDefault = [
  "Subject line order ID does not match screenshot ID",
  "Email about the same issue twice in one day",
  "Complaint about multiple emails to 1stdibs account",
  "No Order ID in the email at all",
  "Issue is not actually an issue but support rep's oversight",
  "CCing other distros in an attempt to get a response",
  "Confusion at the given solution",
  "Radio silence when prompted for a response",
  "Acknowledgement of issue resolution not given",
  "No thanks given for helping fix RO",
  "Issue is caused by support rep's error",
  "Issue can be resolved through the RO Guidelines doc",
  "Support rep makes the issue worse in solving attempt",
  "RO is the wrong group for the issue to solve",
  "Incorrect amounts entered into the refund modal",
  "RO about high value processing declined",
  "RO about wire transfer adjustments",
  "Support rep is a jerk",
  "RO is missing screenshots where it would be useful",
  "Issue is already in Currently Known Issues",
  "Flood of RO's related to newly introduced bug",
  "Vague, unhelpful e-mail title",
  "Vague, unhelpful e-mail body",
  "Help request initially sent to the wrong distro",
  "Issue resolves itself before RO does anything",
];

module.exports = BingoDefault;
